baseURL = "https://cpondoc.github.io/"
languageCode = "en-us"
title = "My Hugo Blog"
theme = "hugo-book"

[params]
  author = "Your Name"
  description = "A blog powered by Hugo"
  showToC = true  # Show table of contents
  BookToC = true
  # Other theme-specific options can be added here.